// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file_service.proto

package com.grpc.service;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.grpc.gen.Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();
}
