// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file_service.proto

package com.grpc.service;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.grpc.gen.Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 length = 1;</code>
   * @return The length.
   */
  int getLength();

  /**
   * <code>bytes bs = 2;</code>
   * @return The bs.
   */
  com.google.protobuf.ByteString getBs();
}
